apiVersion: 1

datasources:
- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: true
  version: 1
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://mimir:9009/prometheus
  basicAuth: false
  version: 1
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  jsonData:
    httpHeaderName1: "X-Scope-OrgID"
  secureJsonData:
    httpHeaderValue1: "tenant1"
